// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"examples/pkg/adapter/handler"
	"examples/pkg/adapter/infra"
	"examples/pkg/adapter/repository"
	"examples/pkg/logic"
)

// Injectors from wire.go:

func InitializeContainer(sqlh infra.SqlHandler) *handler.UserHandler {
	userRepository := repository.NewUserRepository(sqlh)
	loginRepository := repository.NewLoginRepository(sqlh)
	userLogic := logic.NewUserLogic(userRepository, loginRepository)
	userHandler := handler.NewUserHandler(userLogic)
	return userHandler
}

// wire.go:

type AppController struct {
	User    handler.UserHandler
	Session handler.SessionHandler
}
